package logs

// Err represents most of the errors generated by the package.
type Err string

func (e Err) Error() string {
	return string(e)
}

const (
	// InvalidLevelName occurs when LevelByName is called with an invalid name.
	InvalidLevelName Err = "invalid level name"
)
